# Generated by Django 5.1.2 on 2024-11-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_alter_country_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='group_id',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
