list_by_continent = {
    
    "Africa": {
        'Algeria': 'DZ',
        'Angola': 'AO',
        'Benin': 'BJ',
        'Botswana': 'BW',
        'Burkina Faso': 'BF',
        'Burundi': 'BI',
        'Cabo Verde': 'CV',
        'Cameroon': 'CM',
        'Central African Republic': 'CF',
        'Chad': 'TD',
        'Comoros': 'KM',
        "Côte d'Ivoire": 'CI',
        'Congo': 'CG',
        'Congo, The Democratic Republic Of The': 'CD',
        'Djibouti': 'DJ',
        'Egypt': 'EG',
        'Eritrea': 'ER',
        'Eswatini': 'SZ',
        'Ethiopia': 'ET',
        'Gabon': 'GA',
        'Gambia': 'GM',
        'Ghana': 'GH',
        'Guinea': 'GN',
        'Guinea-Bissau': 'GW',
        'Kenya': 'KE',
        'Lesotho': 'LS',
        'Liberia': 'LR',
        'Libya': 'LY',
        'Madagascar': 'MG',
        'Malawi': 'MW',
        'Mali': 'ML',
        'Mauritania': 'MR',
        'Mauritius': 'MU',
        'Mozambique': 'MZ',
        'Namibia': 'NA',
        'Niger': 'NE',
        'Nigeria': 'NG',
        'Rwanda': 'RW',
        'São Tomé And Príncipe': 'ST',
        'Senegal': 'SN',
        'Seychelles': 'SC',
        'Sierra Leone': 'SL',
        'Somalia': 'SO',
        'South Africa': 'ZA',
        'South Sudan': 'SS',
        'Sudan': 'SD',
        'Tanzania, United Republic Of': 'TZ',
        'Togo': 'TG',
        'Uganda': 'UG',
        'Zambia': 'ZM',
        'Zimbabwe': 'ZW'
    },
    
    "Asia": {
        'Afghanistan': 'AF',
        'Armenia': 'AM',
        'Bahrain': 'BH',
        'Bangladesh': 'BD',
        'Bhutan': 'BT',
        'Brunei Darussalam': 'BN',
        'Burma': 'MM',
        'Cambodia': 'KH',
        'China': 'CN',
        'Georgia': 'GE',
        'India': 'IN',
        'Indonesia': 'ID',
        'Iran, Islamic Republic Of': 'IR',
        'Iraq': 'IQ',
        'Israel': 'IL',
        'Japan': 'JP',
        'Jordan': 'JO',
        'Kazakhstan': 'KZ',
        'Kiribati': 'KI',
        "Korea, Democratic People's Republic Of": 'KP',
        'Korea, Republic Of': 'KR',
        'Kuwait': 'KW',
        'Kyrgyzstan': 'KG',
        "Lao People's Democratic Republic": 'LA',
        'Lebanon': 'LB',
        'Malaysia': 'MY',
        'Maldives': 'MV',
        'Mongolia': 'MN',
        'Nepal': 'NP',
        'Oman': 'OM',
        'Pakistan': 'PK',
        'Philippines': 'PH',
        'Qatar': 'QA',
        'Saudi Arabia': 'SA',
        'Singapore': 'SG',
        'Sri Lanka': 'LK',
        'Taiwan, Province Of China': 'TW',
        'Tajikistan': 'TJ',
        'Thailand': 'TH',
        'Timor-Leste': 'TL',
        'Turkmenistan': 'TM',
        'United Arab Emirates': 'AE',
        'Uzbekistan': 'UZ',
        'Viet Nam': 'VN',
        'Yemen': 'YE'
    },
    
    "Europe": {
        'Albania': 'AL',
        'Andorra': 'AD',
        'Austria': 'AT',
        'Belarus': 'BY',
        'Belgium': 'BE',
        'Bosnia And Herzegovina': 'BA',
        'Bulgaria': 'BG',
        'Croatia': 'HR',
        'Cyprus': 'CY',
        'Czech Republic': 'CZ',
        'Denmark': 'DK',
        'Estonia': 'EE',
        'Finland': 'FI',
        'France': 'FR',
        'Germany': 'DE',
        'Greece': 'GR',
        'Hungary': 'HU',
        'Iceland': 'IS',
        'Ireland': 'IE',
        'Italy': 'IT',
        'Latvia': 'LV',
        'Liechtenstein': 'LI',
        'Lithuania': 'LT',
        'Luxembourg': 'LU',
        'Malta': 'MT',
        'Moldova, Republic Of': 'MD',
        'Monaco': 'MC',
        'Montenegro': 'ME',
        'Netherlands': 'NL',
        'North Macedonia': 'MK',
        'Norway': 'NO',
        'Poland': 'PL',
        'Portugal': 'PT',
        'Romania': 'RO',
        'Russian Federation': 'RU',
        'Serbia': 'RS',
        'Slovakia': 'SK',
        'Slovenia': 'SI',
        'Spain': 'ES',
        'Sweden': 'SE',
        'Switzerland': 'CH',
        'Ukraine': 'UA',
        'United Kingdom': 'GB'
    },
    
    "North America": {
        'Antigua And Barbuda': 'AG',
        'Bahamas': 'BS',
        'Barbados': 'BB',
        'Canada': 'CA',
        'Cayman Islands': 'KY',
        'Costa Rica': 'CR',
        'Cuba': 'CU',
        'Dominica': 'DM',
        'Dominican Republic': 'DO',
        'El Salvador': 'SV',
        'Greenland': 'GL',
        'Guatemala': 'GT',
        'Haiti': 'HT',
        'Honduras': 'HN',
        'Jamaica': 'JM',
        'Mexico': 'MX',
        'Nicaragua': 'NI',
        'Panama': 'PA',
        'Puerto Rico': 'PR',
        'Saint Kitts And Nevis': 'KN',
        'Saint Lucia': 'LC',
        'Saint Vincent And The Grenadines': 'VC',
        'United States': 'US',
        'United States Minor Outlying Islands': 'UM'
    },
    
    "South America": {
        'Argentina': 'AR',
        'Bolivia, Plurinational State Of': 'BO',
        'Brazil': 'BR',
        'Chile': 'CL',
        'Colombia': 'CO',
        'Ecuador': 'EC',
        'Guyana': 'GY',
        'Paraguay': 'PY',
        'Peru': 'PE',
        'Suriname': 'SR',
        'Uruguay': 'UY',
        'Venezuela, Bolivarian Republic Of': 'VE'
    },

     "Oceania": {
        'Australia': 'AU',
        'Fiji': 'FJ',
        'Kiribati': 'KI',
        'Marshall Islands': 'MH',
        'Micronesia, Federated States Of': 'FM',
        'Nauru': 'NR',
        'New Zealand': 'NZ',
        'Papua New Guinea': 'PG',
        'Samoa': 'WS',
        'Solomon Islands': 'SB',
        'Tonga': 'TO',
        'Tuvalu': 'TV',
        'Vanuatu': 'VU'
    }
}
